### ISSUE TITLE
Not Found in some routes

### ISSUE THREAD

**Issue by duard** [tutts/es6-express-mongoose-passport-rest-api#4]
Hi, thanks for sharing this code.

When i try to access /auth/me after authenticate i give

```
**{
    "message": "Not Found",
    "stack": "Error: API not found\n    at APIError.ExtendableError (/Users/duard/Development/api-es6/src/server/helpers/APIError.js:14:11)\n    at new APIError (/Users/duard/Development/api-es6/src/server/helpers/APIError.js:29:85)\n    at /Users/duard/Development/api-es6/src/config/express.js:88:15\n    at Layer.handle [as handle_request] (/Users/duard/Development/api-es6/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:312:13)\n    at /Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:271:10)\n    at Layer.handle [as handle_request] (/Users/duard/Development/api-es6/node_modules/express/lib/router/layer.js:91:12)\n    at trim_prefix (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:312:13)\n    at /Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:330:12)\n    at Immediate.next (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:271:10)\n    at Immediate.<anonymous> (/Users/duard/Development/api-es6/node_modules/express/lib/router/index.js:618:15)\n    at runCallback (timers.js:783:20)\n    at tryOnImmediate (timers.js:743:5)"
}
```**

**Comment by duard** [comment]
Sorry, I found my mistake, I was using POST on POSTMAN

**Comment by tutts** [comment]
Sure thing! I'll be sure the update the docs so its easier to onboard 👍
